import 'server-only';

// The answer key, kept off the client bundle on purpose: index-aligned with QUESTIONS in
// lib/engine.ts (same order). Grading happens in lib/grade.ts, never in the browser.
export const ANSWERS: [a: number, e: string][] = [
  [1,"AI is about machines doing things like understanding language, recognising images or making decisions, which usually need human intelligence."],
  [1,"Data is the fuel of AI: models learn patterns from large amounts of examples."],
  [1,"Generative AI produces new content: essays, images, code, audio and more."],
  [0,"Speech recognition turns your voice into text so the assistant can understand the request."],
  [3,"Chatbots can \"hallucinate\". Always double-check important information."],
  [3,"In ML, the system finds patterns in examples (data) rather than following hand-written rules for every case."],
  [2,"A calculator follows fixed arithmetic rules; it does not learn or make intelligent judgements."],
  [0,"Face unlock uses computer vision to recognise your face."],
  [1,"Recommendation systems learn from what you and similar people watched."],
  [2,"AI = Artificial Intelligence: machines doing tasks that normally need human intelligence."],
  [3,"Generative AI creates new content such as text, images or music."],
  [0,"Models learn patterns from many examples. Labels tell them which photos are cats."],
  [1,"It predicts travel time from huge amounts of historical and real-time traffic data."],
  [2,"Use AI to understand, not to replace your own thinking. Always check and rewrite."],
  [3,"Classification means assigning each item to a category."],
  [0,"A prompt is the text you type to tell the model what you want."],
  [1,"Chatbots are language models: they generate text one piece at a time."],
  [2,"It uses language patterns learned from large amounts of text to guess what you meant."],
  [3,"Modern generative models produce many kinds of content."],
  [0,"AI can help you understand, but it can be wrong. A qualified person should confirm."],
  [1,"A dataset is the set of examples a model learns from or is tested on."],
  [2,"Training adjusts the model so it gets better at predicting the labels."],
  [3,"Labels are the answers the model tries to learn to predict."],
  [0,"Models copy patterns in their data, including unfair ones. Biased data gives biased decisions."],
  [1,"Almost all AI today is narrow: good at specific tasks, not general intelligence."],
  [2,"Size refers to the number of learned parameters and the scale of training data."],
  [3,"Hallucinations are confident but false outputs. Verify anything important."],
  [0,"Deepfakes use AI to imitate real people’s faces or voices, often to deceive."],
  [1,"Clear prompts state the task, length, audience and tone."],
  [2,"The app first reads the text in the image, then translates it."],
  [3,"Recommendation systems use your browsing history to personalise what you see."],
  [0,"Too little data means the model cannot learn the real pattern."],
  [1,"You describe the image in words and the model draws it."],
  [2,"Chat data may be stored or used for training. Keep private information out."],
  [3,"Computer vision covers tasks like recognising objects, faces and scenes."],
  [0,"Independent sources catch hallucinations. Asking again can repeat the same error."],
  [1,"Unsupervised learning finds structure in data without given answers."],
  [2,"Reinforcement learning learns from rewards and penalties over many attempts."],
  [3,"Artificial neurons pass signals to each other in layers, a loose analogy to the brain."],
  [0,"Language models generate text one token at a time, each predicted from what came before."],
  [1,"For loans, hiring or medicine, people have a right to understand automated decisions."],
  [2,"A model can only be as good as the data it learns from."],
  [3,"Models invent plausible citations. Always verify sources independently."],
  [0,"Alan Turing proposed judging intelligence by whether a human can tell machine from human in conversation."],
  [1,"Unseen test data reveals whether the model learned the pattern or just memorised examples."],
  [2,"Cameras, lidar and radar feed models that detect lanes, cars and pedestrians."],
  [3,"Multimodal models work with text, images, audio or video together."],
  [0,"Filters block things like instructions for weapons or abusive content."],
  [1,"Personal data identifies a person and must be handled carefully."],
  [2,"Models do best on patterns they saw often. Rare names and accents are harder."],
  [0,"Equal logits get equal probability. [0.73, 0.27] is softmax([1, 0]) and [0.88, 0.12] is softmax([2, 0])."],
  [2,"Dividing logits by T → 0 puts all the probability on the highest logit. T = 1 is the unscaled softmax."],
  [0,"Prompt and output share the same context window."],
  [3,"Top-p adapts the candidate set to the distribution, unlike top-k, which keeps a fixed number of tokens."],
  [1,"This is indirect prompt injection. Prompt wording and filters are easily bypassed; separating data from instructions and limiting privileges is the robust defence."],
  [1,"The model receives a few token IDs, not letters, so character-level tasks are hard for it."],
  [3,"Each generated step becomes context for the next, so the model can build the answer incrementally."],
  [0,"Queries are only needed for the new token; caching earlier keys and values avoids recomputing the prefix."],
  [2,"Every token is scored against every other token with a d-dimensional dot product. O(n·d²) is the cost of the projection and feed-forward layers."],
  [3,"They are trained to predict added noise, then start from pure noise and denoise iteratively. The other options describe GANs, autoregressive and one-shot decoders."],
  [2,"LoRA freezes the base model and learns low-rank updates. Soft prompts are prompt tuning, and 4-bit storage is the quantisation part of QLoRA."],
  [3,"Models read and write tokens, which are usually sub-word pieces."],
  [0,"English averages about 1.3 tokens per word, so 750 words is close to 1,000 tokens."],
  [1,"Higher temperature flattens the distribution, so less likely tokens get picked more often."],
  [2,"Zero-shot relies on the model’s general ability. Few-shot adds examples."],
  [3,"Examples in the prompt demonstrate the task without changing the model."],
  [0,"It sets role, rules and style before the user’s messages."],
  [1,"Similar meanings map to nearby vectors, which powers semantic search."],
  [2,"ASR transcribes audio. TTS does the reverse."],
  [3,"OpenAI’s Whisper is a widely used open ASR model. Stable Diffusion makes images, YOLO detects objects."],
  [0,"Optical character recognition turns pictures of text into editable text."],
  [1,"Keep it secret: anyone with the key can make calls billed to you."],
  [2,"Events after the cutoff are unknown to the model unless provided in the prompt or via tools."],
  [3,"Licences differ by tool, and copying a named artist’s style raises legal and ethical issues."],
  [0,"Only the single most likely token is ever chosen."],
  [1,"It lowers the logits of tokens that already appeared, discouraging loops."],
  [2,"Structured output lets programs consume the result without fragile text parsing."],
  [3,"It steers the output but does not add knowledge the model lacks."],
  [0,"Attention mixes information across positions. Feed-forward layers act on each token separately."],
  [1,"Without position information, a transformer treats the input as a bag of tokens."],
  [2,"Embedding models are trained so that semantic similarity gives geometric closeness."],
  [3,"CLIP is trained on image-caption pairs, enabling zero-shot image classification and search."],
  [0,"It lists unwanted features such as \"blurry\" or \"extra fingers\"."],
  [1,"Cloned voices have been used for scams and fake recordings."],
  [2,"Jailbreaks use role-play, encoding tricks or persistence to bypass guardrails."],
  [3,"It caps generation. Prompt size is limited separately by the context window."],
  [0,"Models have no memory beyond the context they are given on each call."],
  [1,"Each head can specialise, for example in syntax or coreference."],
  [2,"Causal masking is what makes next-token prediction well defined."],
  [3,"BPE starts from characters or bytes and merges common pairs until the vocabulary size is reached."],
  [0,"Beam search is a deterministic search for high-probability sequences. It often reduces diversity."],
  [1,"Thought, Action, Observation loops let the model plan and use tools."],
  [2,"Pretraining gives knowledge. SFT on instruction-response pairs makes the model helpful."],
  [3,"Fine-tuning bakes in style and behaviour. RAG supplies fresh, attributable facts."],
  [0,"Working in latent space makes Stable Diffusion far cheaper than pixel-space diffusion."],
  [1,"Higher guidance means stronger prompt adherence, at the cost of diversity and artefacts."],
  [2,"An encoder such as a ViT turns the image into embeddings the LLM attends to."],
  [3,"Around 680k hours of multilingual audio with transcripts gave it robustness to accents and noise."],
  [0,"Keep keys on a server and proxy requests through it."],
  [1,"It adds calibrated noise so no individual record can be reliably recovered."],
  [1,"It compares the predicted class distribution with the true label. Robust regression uses losses like Huber."],
  [0,"A false negative is far costlier than a follow-up test, so recall comes first."],
  [2,"L2 shrinks weights smoothly. The others describe L1, gradient clipping and dropout."],
  [0,"The model is overfitting. Stop at the best validation point and constrain the model."],
  [3,"cos θ = a·b / (‖a‖‖b‖) = a·b when norms are 1. Half the squared distance equals 1 − cos θ."],
  [1,"Without overlap, a sentence split across two chunks may match neither query well."],
  [1,"Lexical and semantic signals fail differently, so fusing them improves recall."],
  [3,"Sigmoid derivatives are at most 0.25 and shrink with depth. ReLU and skip connections keep gradients flowing."],
  [0,"HNSW greedily walks a hierarchy of proximity graphs. The distractors describe KD-trees, LSH and PQ (which is lossy)."],
  [2,"Evaluate the retriever on its own with labelled data, so you know whether failures come from retrieval or generation."],
  [3,"The variance of q·k grows with dₖ. Scaling keeps logits where softmax still has useful gradients; softmax itself makes rows sum to one."],
  [2,"Using running statistics makes predictions independent of how test examples are batched."],
  [2,"Regression predicts numbers. Classification predicts categories."],
  [3,"The test set must stay untouched until the end to avoid optimistic estimates."],
  [0,"With 99% negatives, predicting \"negative\" always scores 99% accuracy."],
  [1,"It steps against the gradient of the loss."],
  [2,"Steps overshoot the minimum. Too low a rate gives slow progress instead."],
  [3,"ReLU is zero for negatives and identity for positives. The second option is the sigmoid."],
  [0,"Common sizes are 384, 768, 1,024, 1,536 and 3,072."],
  [1,"Retrieve relevant documents, then generate an answer grounded in them."],
  [2,"The same embedding model is used for queries so they can be compared."],
  [3,"Nearest-neighbour search over embeddings is its core operation."],
  [0,"Each category becomes its own 0/1 column."],
  [1,"An epoch contains many batches, each causing one update."],
  [2,"Each fold serves as validation once, averaging out the luck of a single split."],
  [3,"The harmonic mean punishes a large gap between precision and recall."],
  [0,"AUC is the chance a random positive is ranked above a random negative."],
  [1,"Bagging plus feature randomness decorrelates the trees so their errors average out."],
  [2,"Each new tree corrects what the previous ones got wrong."],
  [3,"It prevents co-adaptation, acting like an ensemble of thinned networks."],
  [0,"Adam keeps running averages of gradients and squared gradients."],
  [1,"A small filter slides over the image, so the same feature detector works everywhere."],
  [2,"Cross-encoders read query and passage together, which is accurate but too slow for the whole corpus."],
  [3,"One embedding for a long chunk blurs many topics together."],
  [0,"Distances are only meaningful between vectors from the same model."],
  [1,"Filters keep results relevant and enforce access boundaries."],
  [2,"The assumption is rarely true, yet the classifier often works well anyway."],
  [3,"The decoder queries the encoded source sequence."],
  [0,"Skip connections let each block learn a correction to the identity."],
  [1,"That independence from batch size is why transformers use LayerNorm."],
  [2,"It can fit anything, including noise, so it varies a lot between training sets."],
  [3,"Examples: scaling using test statistics, or duplicates across splits."],
  [0,"Warmup avoids early instability. Decay lets the final steps be small."],
  [1,"Evaluate retrieval and generation separately so you fix the right stage."],
  [2,"A hypothetical answer looks more like the documents than a short question does."],
  [3,"Several reformulations widen the net for the retriever."],
  [0,"Vectors are split into sub-vectors, each replaced by a small codebook index."],
  [1,"The most important information is packed into the leading dimensions."],
  [2,"Cross-entropy training is maximum likelihood for classification."],
  [3,"Bidirectional context makes BERT strong for understanding, not generation."],
  [0,"The reward model is only accurate near the data it was trained on; without the KL leash the policy finds reward-hacking outputs."],
  [2,"DPO optimises a closed-form loss on preference pairs that implicitly defines the reward. It still uses a reference model and is usually run after SFT."],
  [3,"Accepting draft tokens with probability min(1, p/q) and resampling from the residual reproduces the target distribution exactly while saving latency."],
  [2,"Contiguous per-request KV buffers waste memory through fragmentation and over-reservation; paging lets the server pack far more concurrent sequences."],
  [1,"With static batching, short requests wait for the longest one. Shared prefixes are a different technique: prefix caching."],
  [0,"Separating control flow from untrusted data means injected text can never choose which tools run, rather than hoping a model detects it."],
  [2,"Wang et al. (2022) marginalise over sampled chains of thought by majority vote. Repeated greedy decoding just gives the same answer each time."],
  [0,"It is one minus the probability that all k samples drawn without replacement fail (Chen et al., 2021). Plugging c/n into 1 − (1 − p)ᵏ is biased."],
  [3,"Fewer, relevant tools in context improve selection. A bigger window does not stop distractor tools from confusing the model."],
  [1,"This is reward hacking (Goodhart’s law). Fix the environment so the exploit is impossible and the reward unforgeable; prompts and KL only slow it down."],
  [1,"GRPO drops the critic: advantage = (r − mean of the group) / std of the group, which saves memory and suits verifiable rewards."],
  [3,"Tensor parallelism communicates inside every layer, forward and backward. Pipeline parallelism sends point-to-point activations, and data parallelism syncs once per step."],
  [0,"Beyond about 6.7B parameters, systematic outlier features emerge. A shared scale crushes every other value to zero, so outliers are handled in fp16."],
  [2,"Tool descriptions go straight into the model’s context, so a malicious or compromised server can inject instructions. Pin and review server definitions."],
  [0,"Agents take multiple steps and act on the world through tools."],
  [1,"The model never runs code itself. Your application does, then feeds back the result."],
  [2,"MCP is a client-server protocol so any tool server works with any compatible client."],
  [3,"Nodes are steps, edges are transitions, and state persists across them."],
  [0,"You define agents with roles and goals, then tasks they work on together."],
  [1,"Human preferences train a reward model, which then guides RL."],
  [2,"Prefill is compute-bound. Decode is the token-by-token phase."],
  [3,"Generating one token does little arithmetic per byte moved, so bandwidth dominates."],
  [0,"It scales evaluation but needs calibration against human judgements."],
  [1,"A gateway centralises keys, quotas, retries and tracing."],
  [2,"It limits the damage a hijacked or mistaken agent can do."],
  [3,"Test-time compute scaling trades latency for accuracy on hard problems."],
  [0,"State carried across steps is what makes multi-step plans coherent."],
  [1,"Vague descriptions cause wrong tool choice and malformed arguments."],
  [2,"Tools have side effects. Resources are read-only context."],
  [3,"Checkpointed state lets the graph resume after a human decides."],
  [0,"It learns to predict which of two responses humans prefer."],
  [1,"It is a simple way to distil a verifier’s signal back into the policy."],
  [2,"The shared prefix’s KV cache is computed once and reused."],
  [3,"It is exact attention with far less memory traffic."],
  [0,"Iterating on the test set turns it into a training set."],
  [1,"It searches over partial solutions instead of committing to one path."],
  [2,"Instructions arrived through untrusted data, not from the user."],
  [3,"Canaries catch regressions with limited blast radius."],
  [0,"The model judges responses against a \"constitution\", producing preference data at scale."],
  [1,"Clipping the probability ratio keeps updates conservative and stable."],
  [2,"Earlier models were undertrained. Hoffmann et al. (2022) showed data matters as much as size."],
  [3,"Total parameters are large, but only a fraction is active per token."],
  [0,"The dot product then depends on relative position, which helps length generalisation."],
  [1,"Fewer KV heads means less memory traffic during decode."],
  [2,"Separating them avoids long prefills stalling latency-sensitive decode steps."],
  [3,"Summarising state and verifying intermediate results mitigates this."],
  [0,"It is the standard benchmark for coding agents."],
  [1,"Run untrusted code in isolated containers or microVMs with no secrets mounted."],
  [2,"Step-level feedback helps search and training on multi-step problems."],
  [3,"Grammar-constrained decoding fixes the shape, not the truth, of the output."],
];
